packages:
  - "apps/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  prisma-zod-generator: true
  sharp: true
  unrs-resolver: true

<<<<<<< HEAD
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - bcrypt
  - prisma
  - prisma-zod-generator
  - sharp
  - unrs-resolver
=======


>>>>>>> dev
